# Generated by Django 5.2.6 on 2025-09-07 09:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskaid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydrationlog',
            old_name='amount_ml',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='studysession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blink',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blink',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blink_events', to='taskaid.studysession'),
        ),
        migrations.AlterField(
            model_name='hydrationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hydration_logs', to='taskaid.studyuser'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='taskaid.studyuser'),
        ),
        migrations.AlterField(
            model_name='posture',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postures', to='taskaid.studysession'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='taskaid.studyuser'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='taskaid.studyuser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskaid.studyuser'),
        ),
    ]
