# Generated by Django 6.0.5 on 2026-05-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskaid', '0002_rename_amount_ml_hydrationlog_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Mathematics'), ('science', 'Science'), ('history', 'History'), ('language', 'Language Arts'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blink',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blink_events', to='taskaid.studysession'),
        ),
        migrations.AlterField(
            model_name='hydrationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hydration_logs', to='taskaid.studyuser'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='taskaid.studyuser'),
        ),
        migrations.AlterField(
            model_name='posture',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postures', to='taskaid.studysession'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='taskaid.studyuser'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='taskaid.studyuser'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='taskaid.studyuser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskaid.studyuser'),
        ),
    ]
